version: "3"
services:
  app:
    image: ${IMAGE}
    container_name: nodeapp
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - EMAIL=fsecon.booking@gmail.com
      - DB_URI=mongodb://admin:password@mongodb
      - api-key=193d37fe7ccd0b41fa0bb7e50c72a4f5-1d8af1f4-08d63239
      - domain=sandbox3623c2d0cc094602850534a16d6ff3e1.mailgun.org
      - password=hazem12345.
      - JWT_SECRET=SZ5+'3eE)hhDbpNF
      - JWT_RESET_PASSWORD=:'~.vJ!T>\2^3t?\
      - JWT_ACCOUNT_ACTIVATION=jWAJM#6PE53@a")t
      - GO=bhbdhf
    depends_on:
      - mongodb
    networks:
      - node-network
  mongodb:
    image: mongo
    container_name: mongoo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - data:/data/db
    networks:
      - node-network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - node-network
volumes:
  data:
    driver: local
networks:
  node-network:
    driver: bridge
