version: "3"
services:
  app:
    image: ${IMAGE}
    container_name: nodeapp
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - node-network
  mongodb:
    image: mongo
    container_name: mongoo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - data:/data/db
    networks:
      - node-network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - node-network
volumes:
  data:
    driver: local
networks:
  node-network:
    driver: bridge
