version: "3"
services:
  app:
    image: ${IMAGE}
    restart: always
    ports:
      - "5000"
    environment:
      - PORT=${{ secrets.PORT }}
      - EMAIL=${{ secrets.EMAIL }}
      - DB_URI=${{ secrets.DB_URI }}
      - PASSWORD=${{ secrets.PASSWORD }}
      - JWT_SECRET=${{ secrets.JWT_SECRET }}
      - JWT_RESET_PASSWORD=${{ secrets.JWT_RESET_PASSWORD }}
      - JWT_ACCOUNT_ACTIVATION=${{ secrets.JWT_ACCOUNT_ACTIVATION }}
    depends_on:
      - mongodb
      - nginx
    networks:
      - node-network
  nginx: 
    image: hazem06/ncsc_test:nginx 
    container_name: nginx-reverse-proxy
    restart: always
    ports:
      - "80:80"
    networks:
      - node-network
  mongodb:
    image: mongo
    container_name: mongoo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      - MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
    volumes:
      - data:/data/db
    networks:
      - node-network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${{ secrets.ME_CONFIG_MONGODB_ADMINUSERNAME }}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${{ secrets.ME_CONFIG_MONGODB_ADMINPASSWORD }}
      - ME_CONFIG_MONGODB_SERVER=${{ secrets.ME_CONFIG_MONGODB_SERVER }}
    networks:
      - node-network
    depends_on:
      - mongodb
volumes:
  data:
    driver: local
networks:
  node-network:
    driver: bridge
